Add protected assets notes and cleanup jacms tags
entando/entando-docs pull request #219
Opened 2020-11-03 09:23 UTC by joewhite101

This is a starting point for creating protected assets. Probably needs another pass with some depth on rendering those assets into lists but involves some JSP tag development documentation that is out of scope for this story (i think).

2020-11-03 09:27 UTC, joewhite101 commented
Published to stage:
https://entando.github.io/entando-docs/next/tutorials/cms/creating-protected-resources.html

2020-11-03 19:44 UTC, nshaw requested changes
See https://github.com/entando/entando-docs/pull/220 for my requested changes.

2020-11-03 19:45 UTC, nshaw commented on vuepress/docs/next/tutorials/cms/creating-protected-resources.md
> +1. Create a new page. Assign values as you see fit. (see here if you need steps to create a page TODO).
I went ahead and dropped this TODO for now.

2020-11-04 08:16 UTC, joewhite101 commented on vuepress/docs/next/tutorials/cms/creating-protected-resources.md
> +1. Create a new page. Assign values as you see fit. (see here if you need steps to create a page TODO).
Oops. Meant to remove that. Thanks

2020-11-04 22:23 UTC, nshaw approved these changes

2020-11-04 22:23 UTC, merged