ENDOC-161 Add the Application Wizard page.
entando/entando-docs pull request #230
Opened 2020-11-20 21:43 UTC by nshaw

2020-11-20 21:44 UTC, nshaw commented
Language may change slightly based on questions I have sent to Product but this should be close.

2020-11-23 10:24 UTC, joewhite101 requested changes
One small note.

2020-11-23 10:24 UTC, joewhite101 commented on vuepress/docs/next/tutorials/cms/app-builder/hello-world.md
> +    -   At bottom of the page, selectADD
Missing a space. Maybe unintentional edit.

2020-11-23 14:04 UTC, nshaw commented on vuepress/docs/next/tutorials/cms/app-builder/hello-world.md
> +    -   At bottom of the page, selectADD
Good catch, fixed.

2020-11-24 08:00 UTC, joewhite101 approved these changes
LGTM

2020-11-24 08:00 UTC, merged