ENDOC-391 Added note to Known Issues
entando/entando-docs pull request #368
Opened 2021-12-15 20:29 UTC by Lyd1aCla1r3

Add a release note re docker hub numeric account names breaking deployment of plugins

2021-12-15 22:10 UTC, nshaw requested changes
Looks good, let's add it to next and we're set.

2021-12-16 01:04 UTC, Lyd1aCla1r3 commented
next doesn't have an analogous release notes section... should we create one?

2021-12-16 02:13 UTC, nshaw commented
> next doesn't have an analogous release notes section... should we create one?

Right, good call. I guess let's just leave it there. It probably deserves a permanent reference at some point but I'm not sure how it should be handled.

2021-12-16 02:13 UTC, nshaw approved these changes

2021-12-16 02:13 UTC, merged