Endoc 414C new PR with cleaned up branch
entando/entando-docs pull request #411
Opened 2022-02-04 16:56 UTC by jyunmitch

2022-02-04 21:23 UTC, nshaw requested changes

2022-02-04 21:23 UTC, nshaw commented on vuepress/docs/.vuepress/next.js
> +                        title: 'Entando Platform',
I think we should keep it simpler (switching #3 and #4).
- Overview
- Getting Started
- Solution Template
- Development Process
- Entando Architecture

It looks like we need to add Solution Templates to 6.3.2?

2022-02-05 21:41 UTC, Lyd1aCla1r3 reviewed
apologies once again for the extensive feedback... take it or leave it!

please me know if you disagree with anything i suggested; that will influence my writing moving forward

2022-02-05 21:41 UTC, Lyd1aCla1r3 commented on vuepress/docs/next/docs/getting-started/development-concepts.md
> +Business IT groups and developers Compose an Application with the Entando App Builder, a low-code composition UI. Assemble or update an application from the components already built in step one, addi
agree with leading with target user, as is done in revised Curate and Share description

would change Business IT groups to Business units; BU is a common acronym used in this context

should use full name of Entando Component Repository for consistent naming convention and to clarify that the Manager and Repository are two separate entities; also add links

sample rephrasing: "Business units and developers Compose an application with the Entando App Builder, a low-code composition UI. Assemble or update an application from pre-built components, including templates, widgets and PBCs to add functionality. The Entando Component Manager and Entando Component Repository are integrated into the App Builder for flexible and agile component management."

2022-02-05 21:41 UTC, Lyd1aCla1r3 commented on vuepress/docs/next/docs/getting-started/development-concepts.md
> +In the Consume step, the end-user or consumer interacts with an application to complete specific tasks, the runtime phase of an Entando Application. The modular design of the platform allows the appl
how is an end user different from a consumer? should be obvious the user is the one consuming. would remove hyphen and "consumer"

first sentence is awkward... not explicit if consumer interaction or task completion is the runtime phase; don't think mention of runtime phase adds value... nothing unique to Entando with respect to runtime and the concept of runtime isn't relevant here

sample rewording: "The end user Consumes content by interacting with an application to complete specific tasks. The modular design of the Entando Platform enables intelligent scaling of applications and services. This modularity also allows applications to be iteratively improved by adding or updating content, modifying engine operation, and deploying seamless upgrades to individual components."

2022-02-08 18:17 UTC, Lyd1aCla1r3 commented on vuepress/docs/next/docs/getting-started/development-concepts.md
> +The first step in building a modern application on Entando is to design and create each independant component or functional block for your application. Developers can use the Entando Component Genera
allowing new business capabilities to integrate is equivalent to saying they can be integrated... neither phrasing impacts other components and the optional language is preserved

i would still use Entando Blueprint... only one instance of entando in that paragraph and it's important to clarify that the repo and blueprint are separate entities. if you include links to each that helps, but you're introducing an entando-branded thing, so should make that clear. just my 2 cents. again :P

2022-02-08 18:19 UTC, Lyd1aCla1r3 commented on vuepress/docs/next/docs/getting-started/development-concepts.md
> +With the Entando Platform, the development of an application is organized into distinct steps: create, curate, compose, and consume. In the simplest terms, you start by **creating** functional buildi
i can get behind that, too. but would be consistent with "you" or a particular user role.

2022-02-08 21:15 UTC, nshaw requested changes

2022-02-08 21:15 UTC, nshaw commented on vuepress/docs/.vuepress/next.js
> +                        title: 'Entando Platform',
@jyunmitch I don't think these changes made it in. I'm adding a PR with that and a couple other suggestions.

2022-02-08 21:15 UTC, nshaw commented on vuepress/docs/.vuepress/next.js
> +                        title: 'Entando Platform',
https://github.com/entando/entando-docs/pull/417/files

2022-02-08 22:50 UTC, nshaw approved these changes

2022-02-08 22:50 UTC, merged

2022-02-09 19:10 UTC, Lyd1aCla1r3 reviewed
i really liked your choice of "adapt" wrt engine rules, and how you clarified that Consume is the execution stage - not limited to end user actions. that encompasses runtime + users without being overly wordy and explicit

2022-02-09 19:10 UTC, Lyd1aCla1r3 commented on vuepress/docs/next/docs/getting-started/development-concepts.md
> +In the development lifecycle of an application, Consume is the execution stage where end users interact with the app to complete certain tasks. For an Entando application, the modular design of the c
"In" an Entando Application, not "for"

Entando Application -> capitalize

same comment wrt "means"
tagging ".., according to those interactions" on the end is awkward

what are upgrades outside of adding/editing content and adapting engine rules? if upgrades fall within those categories mentioning upgrades is redundant. seamless upgrades comprise improvements to content and engine rules 

use of "thus" is awkward