ENDOC-414E capitalizations
entando/entando-docs pull request #421
Opened 2022-02-10 21:17 UTC by jyunmitch

2022-02-10 21:28 UTC, nshaw approved these changes

2022-02-10 21:35 UTC, Lyd1aCla1r3 commented on vuepress/docs/next/docs/getting-started/development-concepts.md
> +The first step in building a modern application on Entando is to design and create each independent component or functional block. Developers can use the [Entando Component Generator](../create/compo
one last play...

can we rephrase to "Apps built on Entando leverage a modular design to integrate new business capabilities without reworking existing systems" ?? same kind of thing for other sentences with "means"??

if "no" i'll forever hold my peace...

2022-02-10 21:58 UTC, Lyd1aCla1r3 approved these changes

2022-02-11 19:28 UTC, nshaw requested changes

2022-02-11 19:28 UTC, nshaw commented on vuepress/docs/next/docs/getting-started/development-concepts.md
> +With the Entando Platform, the development of an application is organized into four distinct stages: Create, Curate, Compose, and Consume. In the simplest terms, you **Create** functional building bl
Next still shows the caps.

2022-02-11 19:38 UTC, nshaw approved these changes

2022-02-11 19:38 UTC, merged