ENDOC-467 Update the Google GKE install guide for 7.0
entando/entando-docs pull request #484
Opened 2022-04-12 18:41 UTC by Lyd1aCla1r3

2022-04-15 13:40 UTC, jyunmitch commented on vuepress/docs/next/tutorials/getting-started/gke-install.md
> +8. Select "e2-standard-2" as the Machine Type if you are setting up a basic test cluster for a single Entando Application. Additional CPU and memory may be required for a shared cluster containing mu
should Machine Type be backticked?

2022-04-15 13:40 UTC, jyunmitch commented on vuepress/docs/next/tutorials/getting-started/gke-install.md
> +These are the mimimum instructions to prepare the NGINX ingress using the Google Cloud Shell. Refer to <https://cloud.google.com/community/tutorials/nginx-ingress-gke> and <https://kubernetes.github.
second sentence, change links to text? easier to absorb >> For installation using your local `kubectl` or to vary other settings, refer to [Ingress with NGINX](https://cloud.google.com/community/tutorials/nginx-ingress-gke) and [GCE-GKE details](https://kubernetes.github.io/ingress-nginx/deploy/#gce-gke)

2022-04-15 13:40 UTC, jyunmitch commented on vuepress/docs/next/tutorials/getting-started/gke-install.md
> +Bypass an invalid login form and redirect when using TLS using this workaround.
a bit confusing >> Bypass an invalid login form and redirect when using TLS with this workaround 

not sure if this is what was meant

2022-04-15 13:40 UTC, jyunmitch commented on vuepress/docs/next/tutorials/getting-started/gke-install.md
> +You do not need clustered storage to scale an Entando Application if you schedule all instances to the same node using a `ReadWriteOnce (RWO)` policy and taints on other nodes. Be aware of the impact
using a `ReadWriteOnce (RWO)` policy, and taints on other nodes. 

You only need that comma if the node using RWO and taints are different.  It makes the distinction more clear.

2022-04-18 14:21 UTC, jyunmitch approved these changes

2022-04-18 16:37 UTC, nshaw requested changes

2022-04-18 16:55 UTC, nshaw approved these changes

2022-04-18 18:06 UTC, merged