ENDOC-485 add client role instruction to v632
entando/entando-docs pull request #495
Opened 2022-04-19 18:54 UTC by jyunmitch

The Customer Portal page looks like I made a lot of changes but I just switched the order of sections around. I moved the configuration of CP below the configuration of the Keycloak management. Thought that made more sense since the Keycloak part sets up the management of the CP.

2022-04-19 19:05 UTC, nshaw requested changes

2022-04-19 19:05 UTC, nshaw commented on vuepress/docs/v6.3.2/tutorials/solution/customer-portal.md
> +       1. From the left sidebar, go to `Clients` and select client ID `pn-a71d68dd-166dc0f4-entandodemo-customerportal-server`.
This is the 7.0 client id. We need to use the 6.3.2 client id here.

2022-04-19 19:05 UTC, nshaw commented on vuepress/docs/v6.3.2/tutorials/solution/pda-tutorial.md
> +- Select `pn-efbd66b6-b0ceabd7-entando-pda-plugin-server` from `Client Roles`.
Sorry, I missed this on the last review. This is the 7.0 client id. We need to switch back to the 6.3.2 client id for this tutorial.

2022-04-19 19:05 UTC, nshaw commented on vuepress/docs/v6.3.2/tutorials/solution/customer-portal.md
> +   - Give at least one user the ability to manage the Customer Portal by granting the `cp-admin` role. Assign the `cp-admin` role for the `pn-a71d68dd-166dc0f4-entandodemo-customerportal-server` clie
Change to the 6.3.2 client id.

2022-04-19 19:05 UTC, nshaw commented on vuepress/docs/v6.3.2/tutorials/solution/customer-portal.md
> +   - Give at least one user the ability to manage the Customer Portal by granting the `cp-admin` role. Assign the `cp-admin` role for the `pn-a71d68dd-166dc0f4-entandodemo-customerportal-server` clie
entandodemo-customerportal-server

2022-04-19 19:05 UTC, nshaw commented on vuepress/docs/v6.3.2/tutorials/solution/pda-tutorial.md
> +- Select `pn-efbd66b6-b0ceabd7-entando-pda-plugin-server` from `Client Roles`.
entando-pda-plugin-server

2022-04-20 16:21 UTC, Lyd1aCla1r3 approved these changes

2022-04-20 16:22 UTC, nshaw approved these changes

2022-04-20 16:22 UTC, merged