ENDOC-491 update bundle-uninstall page
entando/entando-docs pull request #503
Opened 2022-04-27 19:20 UTC by jyunmitch

2022-04-27 19:35 UTC, Lyd1aCla1r3 commented on vuepress/docs/v7.0/docs/curate/ecr-uninstall-flow.md
> +If any of the components are in use, a popup alerts you and you must unpublish the content and remove the components. You can't force the removal of a bundle if any component is in use or linked. Eac
pop-up

2022-04-27 19:35 UTC, Lyd1aCla1r3 commented on vuepress/docs/v7.0/docs/curate/ecr-uninstall-flow.md
> +1. Click the `Installed` button next to the bundle and a popup window opens with the options to update the bundle version or uninstall.
pop-up

"update or uninstall the bundle version" (reads better to have the verbs explicitly acting on the subject)

2022-04-27 19:35 UTC, Lyd1aCla1r3 commented on vuepress/docs/v7.0/docs/curate/ecr-uninstall-flow.md
> +When an application bundle is installed in the Entando App Builder, or from the Entando Hub, the advantage is that you can upgrade, downgrade or uninstall at any time. You can upgrade the bundle as a
the second sentence reads haltingly because you're expecting "or" to introduce an alternative "whole," not a different kind of upgrade

2022-04-27 21:07 UTC, nshaw approved these changes

2022-04-27 21:07 UTC, nshaw commented on vuepress/docs/v7.0/docs/curate/ecr-uninstall-flow.md
> +check out the [Troubleshooting guide](./ecr-troubleshooting-guide.md) or the [Entando Forum](https://forum.entando.org).
Maybe we need to bump that ecr-troubleshooting-guide up the priority list. I thought we could use ENDOC-319 but it's not quite the same.

2022-04-28 16:25 UTC, nshaw requested changes

2022-04-28 18:33 UTC, nshaw approved these changes

2022-04-28 18:46 UTC, Lyd1aCla1r3 approved these changes
i'd change "has the ability to be" to "can be"...

2022-04-28 18:59 UTC, merged