ENDOC-532-Run-Dev tutorial update
entando/entando-docs pull request #543
Opened 2022-08-02 14:49 UTC by jyunmitch

2022-08-02 17:27 UTC, Lyd1aCla1r3 commented on vuepress/docs/next/tutorials/create/ms/run-local.md
> +4.  When the widget starts, a browser window opens, with the widget URL
same comment as above

2022-08-02 17:27 UTC, Lyd1aCla1r3 commented on vuepress/docs/next/tutorials/create/ms/run-local.md
> +4. When the widget starts, a browser window opens, with the widget URL
same as above

2022-08-02 17:27 UTC, Lyd1aCla1r3 commented on vuepress/docs/next/tutorials/create/ms/run-local.md
> +5. If you’re not logged in, you’re redirected to the login page
another same as above but wasn't reworded to "it" here

2022-08-02 17:27 UTC, Lyd1aCla1r3 commented on vuepress/docs/next/tutorials/create/ms/run-local.md
> +If you want to use another Keycloak installation or change the service-URL of your widget, change the parameters set in the `.env.local` file that was generated by the Entando Blueprint in the root f
if you want to -> to

file that was generated -> file generated

2022-08-02 17:27 UTC, Lyd1aCla1r3 commented on vuepress/docs/next/tutorials/create/ms/run-local.md
> +By default these variables are set to:
By default,

2022-08-02 17:27 UTC, Lyd1aCla1r3 commented on vuepress/docs/next/tutorials/create/ms/run-local.md
> +2. By default, Docker Compose will recreate the Keycloak container and reset the H2 database each time it is started. To persist Keycloak changes across restarts, you can make the following changes:
use present tense -> recreates / resets / it starts (first sentence)

change one of "changes" (reuse of this word stands out)

2022-08-02 17:27 UTC, Lyd1aCla1r3 commented on vuepress/docs/next/tutorials/create/ms/run-local.md
> +   * Keycloak changes should now be persistent. You can reset your Keycloak database by emptying the `src/main/docker/keycloak-db` directory and restarting the container.
sometimes file paths are backticked and sometimes they're not; since all usage is the same we should be consistent

2022-08-02 17:27 UTC, Lyd1aCla1r3 commented on vuepress/docs/next/tutorials/create/ms/run-local.md
> +3. `User is not authenticated` Error message: If you see this message when you run the widgets,  it is likely that your Keycloak application is not running. Check if the Docker Compose command is sti
"when you run the" -> while running

remove extra space after widgets,

2022-08-02 18:03 UTC, nshaw requested changes

2022-08-02 18:03 UTC, nshaw commented on vuepress/docs/next/tutorials/create/ms/run-local.md
> +If you want to use custom data, edit the `index.html` file in the public folder ui/widgets/YOUR-ENTITY-NAME/detailsWidget/public. Change the "id" attribute in this line:
Same as above, "If you want to view the details for a different row in the database..."

2022-08-02 18:03 UTC, nshaw commented on vuepress/docs/next/tutorials/create/ms/run-local.md
As we discussed, add a note here explaining this tutorial is specific to bundles based on the JHipster Blueprint with a link to v1 versus v5 language.

2022-08-02 22:57 UTC, jyunmitch commented on vuepress/docs/next/tutorials/create/ms/run-local.md
> +This tutorial is specific to bundles generated with the Entando JHipster Blueprint, which is a Git-based or a v1 bundle. If you have Docker-based project (v5), created on Entando 7.1 or newer, please
@nshaw, I'll work on the comparison document, whether it's a table in the release or a separate doc, and link it in later. I feel like the information needs to be processed a bit with a few tutorials to figure out how best to present it.

2022-08-02 23:07 UTC, jyunmitch commented on vuepress/docs/next/tutorials/create/ms/run-local.md
> +By default these variables are set to:
it doesn't have to have a comma

2022-08-03 17:16 UTC, nshaw approved these changes

2022-08-03 17:16 UTC, merged