ENDOC-743-create-v73
entando/entando-docs pull request #771
Opened 2023-08-28 19:55 UTC by jyunmitch

2023-08-29 11:49 UTC, nshaw requested changes
I don't see the change to package.json which we discussed but other than that and the one change in config.json, this looks good to me. The last check I would make, with the package.json tweak, is to run yarn docs:syncNext. If you did it all correctly, you should get no differences with this setup since next and 7.3 should completely the same, other than landing pages which have the version warnings.

2023-08-29 11:49 UTC, nshaw commented on vuepress/docs/.vuepress/config.js
> +      version: "7.3",
This change should be left until you're ready to activate 7.3

2023-08-30 08:28 UTC, nicpuddu approved these changes

2023-09-06 11:51 UTC, nshaw approved these changes

2023-09-06 15:02 UTC, merged