ENDOC-753-keycloak-oracle
entando/entando-docs pull request #800
Opened 2023-12-11 20:56 UTC by jyunmitch

2023-12-15 08:05 UTC, pietrangelo requested changes
I can't understand how this document is related with the External Keycloak configuration. This article explains how to configure Entando's CRs to use Oracle as an external DB.
@jyunmitch @DiegoScantamburlo maybe we need to add a dedicated page for this?

2023-12-15 08:05 UTC, pietrangelo commented on vuepress/docs/next/tutorials/consume/external-id-management.md
I can't understand how this document is related with the `External Keycloak configuration`. This article explains how to configure Entando's CRs to use Oracle as an external DB.
@jyunmitch @DiegoScantamburlo maybe we need to add a dedicated page for this?

2023-12-21 14:57 UTC, DiegoScantamburlo approved these changes

2023-12-22 09:12 UTC, pietrangelo commented on vuepress/docs/next/tutorials/consume/external-id-management.md
@jyunmitch I think we should add it to the `external databases` page yes.

2023-12-22 09:13 UTC, pietrangelo approved these changes

2024-01-18 21:04 UTC, closed without merging